public enum PropType
{
    Attack = 0,
    AttackSpeed = 1,
    CriticalChance = 2,
    CriticalPercent = 3,
    MoveSpeed = 4,
    MaxHealth = 5,
    DetectionRange = 6,
    HealthRecoverySpeed = 7,
    Armor = 8,
    Luck = 9,
    Dodge = 10,
    LifeSteal = 11,
    PickupRadius = 12,
    ProjectileCount = 13,
    ProjectileSpeed = 14,
    AttackRange = 15,
    KnockbackForce = 18,
    ExperienceGain = 20,
    ShopPriceDiscount = 21,
    WaveGoldRewardBonus = 22,
    DamageReduction = 25,
    HealingPower = 26,
}
